(ns tutorial-cljs.quil-docs)
(def docs
(quote [{:doc "Graphics currently used for drawing. By default it is sketch graphics,\n  but if called inside with-graphics macro - graphics passed to the macro\n  is returned. This method should be used if you need to call some methods\n  that are not implemented by quil. Example:\n  (.beginDraw (current-graphics)).", :name current-graphics, :forms ([])}
{:doc "Writes to the text area of the Processing environment's console.\n  This is often helpful for looking at the data a program is producing.\n  Each call to this function creates a new line of output.\n  Individual elements can be separated with quotes (\"\") and joined with the string concatenation operator (+).\n  Also writes the content of an array to the text area of the Processing environment.\n  This is often helpful for looking at the data a program is producing.\n  A new line is put between each element of the array. This function can only print 1D arrays,\n  but can test to see if the content are null or not null for 2+ dimensional arrays.", :name prc-println, :forms ([msg])}
{:doc "Writes to the console area of the Processing environment.\n  This is often helpful for looking at the data a program is producing.\n  The companion function println() works like print(), but creates a new line of text for each call to the function.\n   Individual elements can be separated with quotes (\"\") and joined with the addition operator (+). ", :name prc-print, :forms ([msg])}
{:doc "Returns sketch object by id of canvas element of sketch.", :name get-sketch-by-id, :forms ([id])}
{:doc "Retrieve sketch-specific state-atom. All changes to the\n  atom will be reflected in the state.\n\n  (set-state! :foo 1)\n  (state :foo) ;=> 1\n  (swap! (state-atom) update-in [:foo] inc)\n  (state :foo) ;=> 2", :name state-atom, :forms ([])}
{:doc "Retrieve sketch-specific state by key. Must initially call\n  set-state! to store state. If no parameter passed whole\n  state map is returned.\n\n  (set-state! :foo 1)\n  (state :foo) ;=> 1\n  (state) ;=> {:foo 1}", :name state, :forms ([] [key])}
{:doc "Set sketch-specific state. May only be called once (ideally in the\n  setup fn).  Subsequent calls have no effect.\n\n  Example:\n  (set-state! :foo 1 :bar (atom true) :baz (/ (width) 2))", :name set-state!, :forms ([& state-vals])}
{:doc "Calculates the absolute value (magnitude) of a number. The\n  absolute value of a number is always positive. Dynamically casts to\n  an int or float appropriately", :name abs, :forms ([n])}
{:doc "The inverse of cos, returns the arc cosine of a value. This\n  function expects the values in the range of -1 to 1 and values are\n  returned in the range 0 to Math/PI (3.1415927).", :name acos, :forms ([n])}
{:doc "Extracts the alpha value from a color.", :name alpha, :forms ([color])}
{:doc "Sets the ambient reflectance for shapes drawn to the screen. This\n  is combined with the ambient light component of environment. The\n  color components set through the parameters define the\n  reflectance. For example in the default color mode, setting x=255,\n  y=126, z=0, would cause all the red light to reflect and half of the\n  green light to reflect. Used in combination with emissive, specular,\n  and shininess in setting the material properties of shapes.", :name ambient-float, :forms ([gray] [x y z])}
{:doc "Sets the ambient reflectance for shapes drawn to the screen. This\n  is combined with the ambient light component of environment. The rgb\n  color components set define the reflectance. Used in combination\n  with emissive, specular, and shininess in setting the material\n  properties of shapes.", :name ambient-int, :forms ([rgb])}
{:doc "Sets the ambient reflectance for shapes drawn to the screen. This\n  is combined with the ambient light component of environment. The\n  color components set through the parameters define the\n  reflectance. For example in the default color mode, setting x=255,\n  y=126, z=0, would cause all the red light to reflect and half of the\n  green light to reflect. Used in combination with emissive, specular,\n  and shininess in setting the material properties of shapes.", :name ambient, :forms ([rgb] [x y z])}
{:doc "Adds an ambient light. Ambient light doesn't come from a specific direction,\n  the rays have light have bounced around so much that objects are\n  evenly lit from all sides. Ambient lights are almost always used in\n  combination with other types of lights. Lights need to be included\n  in the draw to remain persistent in a looping program. Placing them\n  in the setup of a looping program will cause them to only have an\n  effect the first time through the loop. The effect of the\n  parameters is determined by the current color mode.", :name ambient-light, :forms ([red green blue] [red green blue x y z])}
{:doc "Multiplies the current matrix by the one specified through the\n  parameters. This is very slow because it will try to calculate the\n  inverse of the transform, so avoid it whenever possible. The\n  equivalent function in OpenGL is glMultMatrix().", :name apply-matrix, :forms ([n00 n01 n02 n03 n10 n11 n12 n13 n20 n21 n22 n23 n30 n31 n32 n33])}
{:doc "Draws an arc in the display window. Arcs are drawn along the outer\n  edge of an ellipse defined by the x, y, width and height\n  parameters. The origin or the arc's ellipse may be changed with the\n  ellipse-mode function. The start and stop parameters specify the\n  angles at which to draw the arc. The mode is either :open, :chord or :pie.", :name arc, :forms ([x y width height start stop])}
{:doc "The inverse of sin, returns the arc sine of a value. This function\n  expects the values in the range of -1 to 1 and values are returned\n  in the range -PI/2 to PI/2.", :name asin, :forms ([n])}
{:doc "The inverse of tan, returns the arc tangent of a value. This\n  function expects the values in the range of -Infinity to\n  Infinity (exclusive) and values are returned in the range -PI/2 to\n  PI/2 .", :name atan, :forms ([n])}
{:doc "Calculates the angle (in radians) from a specified point to the\n  coordinate origin as measured from the positive x-axis. Values are\n  returned as a float in the range from PI to -PI. The atan2 function\n  is most often used for orienting geometry to the position of the\n  cursor. Note: The y-coordinate of the point is the first parameter\n  and the x-coordinate is the second due to the structure of\n  calculating the tangent.", :name atan2, :forms ([y x])}
{:doc "A sequence of strings representing the fonts on this system\n  available for use.\n\n  Because of limitations in Java, not all fonts can be used and some\n  might work with one operating system and not others. When sharing a\n  sketch with other people or posting it on the web, you may need to\n  include a .ttf or .otf version of your font in the data directory of\n  the sketch because other people might not have the font installed on\n  their computer. Only fonts that can legally be distributed should be\n  included with a sketch.", :name available-fonts, :forms ([])}
{:doc "Sets the color used for the background of the Processing\n  window. The default background is light gray. In the draw function,\n  the background color is used to clear the display window at the\n  beginning of each frame.\n\n  It is not possible to use transparency (alpha) in background colors\n  with the main drawing surface, however they will work properly with\n  create-graphics. Converts args to floats.", :name background-float, :forms ([gray] [gray alpha] [r g b] [r g b a])}
{:doc "Sets the color used for the background of the Processing\n  window. The default background is light gray. In the draw function,\n  the background color is used to clear the display window at the\n  beginning of each frame.\n\n  It is not possible to use transparency (alpha) in background colors\n  with the main drawing surface, however they will work properly with\n  create-graphics. Converts rgb to an int and alpha to a float.", :name background-int, :forms ([rgb] [rgb alpha])}
{:doc "Sets the color used for the background of the Processing\n  window. The default background is light gray. In the draw function,\n  the background color is used to clear the display window at the\n  beginning of each frame.\n\n  It is not possible to use transparency (alpha) in background colors\n  with the main drawing surface, however they will work properly with\n  create-graphics. Converts args to floats.", :name background, :forms ([rgb] [rgb alpha] [r g b] [r g b a])}
{:doc "Specify an image to be used as the background for a sketch. Its\n  width and height must be the same size as the sketch window. Images\n  used as background will ignore the current tint setting.", :name background-image, :forms ([img])}
{:doc "Sets the matrix mode to the camera matrix so calls such as\n  translate, rotate, apply-matrix and reset-matrix affect the\n  camera. begin-camera should always be used with a following\n  end-camera and pairs of begin-camera and end-camera cannot be\n  nested.\n\n  For most situations the camera function will be sufficient.", :name begin-camera, :forms ([])}
{:doc "Use the begin-contour and end-contour function to create negative\n  shapes within shapes. These functions can only be within a\n  begin-shape/end-shape pair and they only work with the :p2d and :p3d\n  renderers.", :name begin-contour, :forms ([])}
{:doc "Enables the creation of complex forms. begin-shape begins recording\n  vertices for a shape and end-shape stops recording. Use the mode\n  keyword to specify which shape create from the provided\n  vertices. With no mode specified, the shape can be any irregular\n  polygon.\n\n  The available mode keywords are :points, :lines, :triangles,\n                                  :triangle-fan, :triangle-strip,\n                                  :quads, :quad-strip.\n\n  After calling the begin-shape function, a series of vertex commands\n  must follow. To stop drawing the shape, call end-shape. The vertex\n  function with two parameters specifies a position in 2D and the\n  vertex function with three parameters specifies a position in\n  3D. Each shape will be outlined with the current stroke color and\n  filled with the fill color.\n\n  Transformations such as translate, rotate, and scale do not work\n  within begin-shape. It is also not possible to use other shapes,\n  such as ellipse or rect within begin-shape.", :name begin-shape, :forms ([] [mode])}
{:doc "Draws a Bezier curve on the screen. These curves are defined by a\n  series of anchor and control points. The first two parameters\n  specify the first anchor point and the last two parameters specify\n  the other anchor point. The middle parameters specify the control\n  points which define the shape of the curve.", :name bezier, :forms ([x1 y1 cx1 cy1 cx2 cy2 x2 y2] [x1 y1 z1 cx1 cy1 cz1 cx2 cy2 cz2 x2 y2 z2])}
{:doc "Sets the resolution at which Beziers display. The default value is\n  20. This function is only useful when using the :p3d or :opengl\n  renderer as the default (:java2d) renderer does not use this\n  information.", :name bezier-detail, :forms ([detail])}
{:doc "Evaluates the Bezier at point t for points a, b, c, d. The\n  parameter t varies between 0 and 1, a and d are points on the curve,\n  and b and c are the control points. This can be done once with the x\n  coordinates and a second time with the y coordinates to get the\n  location of a bezier curve at t.", :name bezier-point, :forms ([a b c d t])}
{:doc "Calculates the tangent of a point on a Bezier curve.\n  (See http://en.wikipedia.org/wiki/Tangent)", :name bezier-tangent, :forms ([a b c d t])}
{:doc "Specifies vertex coordinates for Bezier curves. Each call to\n  bezier-vertex defines the position of two control points and one\n  anchor point of a Bezier curve, adding a new segment to a line or\n  shape. The first time bezier-vertex is used within a begin-shape\n  call, it must be prefaced with a call to vertex to set the first\n  anchor point. This function must be used between begin-shape and\n  end-shape and only when there is no parameter specified to\n  begin-shape.", :name bezier-vertex, :forms ([cx1 cy1 cx2 cy2 x y] [cx1 cy1 cz1 cx2 cy2 cz2 x y z])}
{:doc "Returns a string representing the binary value of an int, char or\n  byte. When converting an int to a string, it is possible to specify\n  the number of digits used.", :name binary, :forms ([val] [val num-digits])}
{:doc "Blends a region of pixels from one image into another with full alpha\n  channel support. If src is not specified it defaults to current-graphics.\n  If dest is not specified it defaults to current-graphics.\n\n  Note: blend-mode function is recommended to use instead of this one.\n\n  Available blend modes are:\n\n  :blend      - linear interpolation of colours: C = A*factor + B\n  :add        - additive blending with white clip:\n                                            C = min(A*factor + B, 255)\n  :subtract   - subtractive blending with black clip:\n                                            C = max(B - A*factor, 0)\n  :darkest    - only the darkest colour succeeds:\n                                            C = min(A*factor, B)\n  :lightest   - only the lightest colour succeeds:\n                                            C = max(A*factor, B)\n  :difference - subtract colors from underlying image.\n  :exclusion  - similar to :difference, but less extreme.\n  :multiply   - Multiply the colors, result will always be darker.\n  :screen     - Opposite multiply, uses inverse values of the colors.\n  :overlay    - A mix of :multiply and :screen. Multiplies dark values\n                and screens light values.\n  :hard-light - :screen when greater than 50% gray, :multiply when\n                lower.\n  :soft-light - Mix of :darkest and :lightest. Works like :overlay,\n                but not as harsh.\n  :dodge      - Lightens light tones and increases contrast, ignores\n                darks.\n                Called \"Color Dodge\" in Illustrator and Photoshop.\n  :burn       - Darker areas are applied, increasing contrast, ignores\n                lights. Called \"Color Burn\" in Illustrator and\n                Photoshop.", :name blend, :forms ([x y width height dx dy dwidth dheight mode] [src-img x y width height dx dy dwidth dheight mode] [src-img dest-img x y width height dx dy dwidth dheight mode])}
{:doc "Blends two color values together based on the blending mode given specified\n  with the mode keyword.\n\n  Available blend modes are:\n\n  :blend      - linear interpolation of colours: C = A*factor + B\n  :add        - additive blending with white clip:\n                                            C = min(A*factor + B, 255)\n  :subtract   - subtractive blending with black clip:\n                                            C = max(B - A*factor, 0)\n  :darkest    - only the darkest colour succeeds:\n                                            C = min(A*factor, B)\n  :lightest   - only the lightest colour succeeds:\n                                            C = max(A*factor, B)\n  :difference - subtract colors from underlying image.\n  :exclusion  - similar to :difference, but less extreme.\n  :multiply   - Multiply the colors, result will always be darker.\n  :screen     - Opposite multiply, uses inverse values of the colors.\n  :overlay    - A mix of :multiply and :screen. Multiplies dark values\n                and screens light values.\n  :hard-light - :screen when greater than 50% gray, :multiply when\n                lower.\n  :soft-light - Mix of :darkest and :lightest. Works like :overlay,\n                but not as harsh.\n  :dodge      - Lightens light tones and increases contrast, ignores\n                darks.\n                Called \"Color Dodge\" in Illustrator and Photoshop.\n  :burn       - Darker areas are applied, increasing contrast, ignores\n                lights. Called \"Color Burn\" in Illustrator and\n                Photoshop.", :name blend-color, :forms ([c1 c2 mode])}
{:doc "Extracts the blue value from a color, scaled to match current color-mode.\n  Returns a float.", :name blue, :forms ([color])}
{:doc "Creates an extruded rectangle.", :name box, :forms ([size] [width height depth])}
{:doc "Extracts the brightness value from a color. Returns a float.", :name brightness, :forms ([color])}
{:doc "Sets the position of the camera through setting the eye position,\n  the center of the scene, and which axis is facing upward. Moving the\n  eye position and the direction it is pointing (the center of the\n  scene) allows the images to be seen from different angles. The\n  version without any parameters sets the camera to the default\n  position, pointing to the center of the display window with the Y\n  axis as up. The default values are:\n\n  eyeX:     (/ (width) 2.0)\n  eyeY:     (/ (height) 2.0)\n  eyeZ:     (/ (/ (height) 2.0) (tan (/ (* Math/PI 60.0) 360.0)))\n  centerX:  (/ (width) 2.0)\n  centerY:  (/ (height) 2.0)\n  centerZ:  0\n  upX:      0\n  upY:      1\n  upZ:      0\n\n  Similar imilar to gluLookAt() in OpenGL, but it first clears the\n  current camera settings.", :name camera, :forms ([] [eyeX eyeY eyeZ centerX centerY centerZ upX upY upZ])}
{:doc "Calculates the closest int value that is greater than or equal to\n  the value of the parameter. For example, (ceil 9.03) returns the\n  value 10.", :name ceil, :forms ([n])}
{:doc "Creates an integer representation of a color The parameters are\n  interpreted as RGB or HSB values depending on the current\n  color-mode. The default mode is RGB values from 0 to 255 and\n  therefore, the function call (color 255 204 0) will return a bright\n  yellow. Args are cast to floats.\n\n  r - red or hue value\n  g - green or saturation value\n  b - blue or brightness value\n  a - alpha value", :name color, :forms ([gray] [gray alpha] [r g b] [r g b a])}
{:doc "Changes the way Processing interprets color data. Available modes\n  are :rgb and :hsb.By default, the parameters for fill, stroke,\n  background, and color are defined by values between 0 and 255 using\n  the :rgb color model. The color-mode fn is used to change the\n  numerical range used for specifying colors and to switch color\n  systems. For example, calling\n  (color-mode :rgb 1.0) will specify that values are specified between\n  0 and 1. The limits for defining colors are altered by setting the\n  parameters range1, range2, range3, and range 4.", :name color-mode, :forms ([mode] [mode max] [mode max-x max-y max-z] [mode max-x max-y max-z max-a])}
{:doc "Constrains a value to not exceed a maximum and minimum value.", :name constrain, :forms ([amt low high])}
{:doc "Copies a region of pixels from the one image to another. If src-img\n  is not specified it defaults to current-graphics. If dest-img is not\n  specified - it defaults to current-graphics. If the source\n  and destination regions aren't the same size, it will automatically\n  resize the source pixels to fit the specified target region. No\n  alpha information is used in the process, however if the source\n  image has an alpha channel set, it will be copied as well. ", :name copy, :forms ([[sx sy swidth sheight] [dx dy dwidth dheight]] [src-img [sx sy swidth sheight] [dx dy dwidth dheight]] [src-img dest-img [sx sy swidth sheight] [dx dy dwidth dheight]])}
{:doc "Calculates the cosine of an angle. This function expects the values\n  of the angle parameter to be provided in radians (values from 0 to\n  Math/PI*2). Values are returned in the range -1 to 1.", :name cos, :forms ([angle])}
{:doc "Dynamically converts a font to the format used by Processing (a\n  PFont) from either a font name that's installed on the computer, or\n  from a .ttf or .otf file inside the sketches 'data' folder. This\n  function is an advanced feature for precise control.\n\n  Use available-fonts to obtain the names for the fonts recognized by\n  the computer and are compatible with this function.\n\n  The size parameter states the font size you want to generate. The\n  smooth parameter specifies if the font should be antialiased or not,\n  and the charset parameter is an array of chars that specifies the\n  characters to generate.\n\n  This function creates a bitmapped version of a font It loads a font\n  by name, and converts it to a series of images based on the size of\n  the font. When possible, the text function will use a native font\n  rather than the bitmapped version created behind the scenes with\n  create-font. For instance, when using the default renderer\n  setting (JAVA2D), the actual native version of the font will be\n  employed by the sketch, improving drawing quality and\n  performance. With the :p2d, :p3d, and :opengl renderer settings, the\n  bitmapped version will be used. While this can drastically improve\n  speed and appearance, results are poor when exporting if the sketch\n  does not include the .otf or .ttf file, and the requested font is\n  not available on the machine running the sketch.", :name create-font, :forms ([name size] [name size smooth] [name size smooth charset])}
{:doc "Creates and returns a new PGraphics object of the types :p2d, :p3d,\n  :java2d, :pdf. By default :java2d is used. Use this class if you\n  need to draw into an off-screen graphics buffer. It's not possible\n  to use create-graphics with the :opengl renderer, because it doesn't\n  allow offscreen use. The :pdf renderer requires the filename parameter.\n\n  Note: don't use create-graphics in draw in clojurescript, it leaks memory.\n  You should create graphic in setup and reuse it in draw instead of creating\n  a new one.\n\n  It's important to call any drawing commands between (.beginDraw graphics) and\n  (.endDraw graphics) statements or use with-graphics macro. This is also true\n  for any commands that affect drawing, such as smooth or color-mode.\n\n  If you're using :pdf renderer - don't forget to call (.dispose graphics)\n  as last command inside with-graphics macro, otherwise graphics won't be\n  saved.\n\n  Unlike the main drawing surface which is completely opaque, surfaces\n  created with create-graphics can have transparency. This makes it\n  possible to draw into a graphics and maintain the alpha channel. By\n  using save to write a PNG or TGA file, the transparency of the\n  graphics object will be honored.", :name create-graphics, :forms ([w h] [w h renderer] [w h renderer path])}
{:doc "Creates a new PImage (the datatype for storing images). This\n  provides a fresh buffer of pixels to play with. Set the size of the\n  buffer with the width and height parameters. The format parameter\n  defines how the pixels are stored. See the PImage reference for more\n  information.\n\n  Possible formats: :rgb, :argb, :alpha (grayscale alpha channel)\n\n  Prefer using create-image over initialising new PImage instances\n  directly.", :name create-image, :forms ([w h format])}
{:doc "Return the current fill color.", :name current-fill, :forms ([])}
{:doc "Return the current stroke color.", :name current-stroke, :forms ([])}
{:doc "Sets the cursor to a predefined symbol or makes it\n  visible if already hidden (after no-cursor was called).\n\n  Available modes: :arrow, :cross, :hand, :move, :text, :wait\n\n  See cursor-image for specifying a generic image as the cursor\n  symbol.", :name cursor, :forms ([] [cursor-mode])}
{:doc "Set the cursor to a predefined image. The horizontal and vertical\n  active spots of the cursor may be specified with hx and hy.\n  It is recommended to make the size 16x16 or 32x32 pixels.", :name cursor-image, :forms ([img] [img hx hy])}
{:doc "Draws a curved line on the screen. The first and second parameters\n  specify the beginning control point and the last two parameters\n  specify the ending control point. The middle parameters specify the\n  start and stop of the curve. Longer curves can be created by putting\n  a series of curve fns together or using curve-vertex. An additional\n  fn called curve-tightness provides control for the visual quality of\n  the curve. The curve fn is an implementation of Catmull-Rom\n  splines.", :name curve, :forms ([x1 y1 x2 y2 x3 y3 x4 y4] [x1 y1 z1 x2 y2 z2 x3 y3 z3 x4 y4 z4])}
{:doc "Sets the resolution at which curves display. The default value is\n  20. This function is only useful when using the :p3d or :opengl\n  renderer as the default (:java2d) renderer does not use this\n  information.", :name curve-detail, :forms ([detail])}
{:doc "Evalutes the curve at point t for points a, b, c, d. The parameter\n  t varies between 0 and 1, a and d are points on the curve, and b c\n  and are the control points. This can be done once with the x\n  coordinates and a second time with the y coordinates to get the\n  location of a curve at t.", :name curve-point, :forms ([a b c d t])}
{:doc "Calculates the tangent of a point on a curve.\n  See: http://en.wikipedia.org/wiki/Tangent", :name curve-tangent, :forms ([a b c d t])}
{:doc "Modifies the quality of forms created with curve and\n  curve-vertex. The parameter squishy determines how the curve fits\n  to the vertex points. The value 0.0 is the default value for\n  squishy (this value defines the curves to be Catmull-Rom splines)\n  and the value 1.0 connects all the points with straight\n  lines. Values within the range -5.0 and 5.0 will deform the curves\n  but will leave them recognizable and as values increase in\n  magnitude, they will continue to deform.", :name curve-tightness, :forms ([ti])}
{:doc "Specifies vertex coordinates for curves. This function may only be\n  used between begin-shape and end-shape and only when there is no\n  mode keyword specified to begin-shape. The first and last points in a\n  series of curve-vertex lines will be used to guide the beginning and\n  end of a the curve. A minimum of four points is required to draw a\n  tiny curve between the second and third points. Adding a fifth point\n  with curve-vertex will draw the curve between the second, third, and\n  fourth points. The curve-vertex function is an implementation of\n  Catmull-Rom splines.", :name curve-vertex, :forms ([x y] [x y z])}
{:doc "Get the current day of the month (1 through 31).", :name day, :forms ([])}
{:doc "Converts a radian measurement to its corresponding value in\n  degrees. Radians and degrees are two ways of measuring the same\n  thing. There are 360 degrees in a circle and (* 2 Math/PI) radians\n  in a circle. For example, (= 90° (/ Math/PI 2) 1.5707964). All\n  trigonometric methods in Processing require their parameters to be\n  specified in radians.", :name degrees, :forms ([radians])}
{:doc "Forces the program to stop running for a specified time. Delay\n  times are specified in thousandths of a second, therefore the\n  function call (delay 3000) will stop the program for three\n  seconds. Because the screen is updated only at the end of draw,\n  the program may appear to 'freeze', because the screen will not\n  update when the delay fn is used. This function has no affect\n  inside setup.", :name delay-frame, :forms ([freeze-ms])}
{:doc "Adds a directional light. Directional light comes from one\n  direction and is stronger when hitting a surface squarely and weaker\n  if it hits at a gentle angle. After hitting a surface, a\n  directional lights scatters in all directions. Lights need to be\n  included in the draw fn to remain persistent in a looping\n  program. Placing them in the setup fn of a looping program will cause\n  them to only have an effect the first time through the loop. The\n  affect of the r, g, and b parameters is determined by the current\n  color mode. The nx, ny, and nz parameters specify the direction the\n  light is facing. For example, setting ny to -1 will cause the\n  geometry to be lit from below (the light is facing directly upward)", :name directional-light, :forms ([r g b nx ny nz])}
{:doc "Calculates the distance between two points", :name dist, :forms ([x1 y1 x2 y2] [x1 y1 z1 x2 y2 z2])}
{:doc "Draws an ellipse (oval) in the display window. An ellipse with an\n  equal width and height is a circle.  The origin may be changed with\n  the ellipse-mode function", :name ellipse, :forms ([x y width height])}
{:doc "Modifies the origin of the ellispse according to the specified mode:\n\n  :center  - specifies the location of the ellipse as\n             the center of the shape. (Default).\n  :radius  - similar to center, but the width and height parameters to\n             ellipse specify the radius of the ellipse, rather than the\n             diameter.\n  :corner  - draws the shape from the upper-left corner of its bounding\n             box.\n  :corners - uses the four parameters to ellipse to set two opposing\n             corners of the ellipse's bounding box.", :name ellipse-mode, :forms ([mode])}
{:doc "Sets the emissive color of the material used for drawing shapes\n drawn to the screen. Used in combination with ambient, specular, and\n shininess in setting the material properties of shapes. Converts all\n args to floats", :name emissive-float, :forms ([float-val] [r g b])}
{:doc "Sets the emissive color of the material used for drawing shapes\n  drawn to the screen. Used in combination with ambient, specular, and\n  shininess in setting the material properties of shapes. Converts all\n  args to ints", :name emissive-int, :forms ([int-val])}
{:doc "Sets the emissive color of the material used for drawing shapes\n  drawn to the screen. Used in combination with ambient, specular, and\n  shininess in setting the material properties of shapes.\n\n  If passed one arg - it is assumed to be an int (i.e. a color),\n  multiple args are converted to floats.", :name emissive, :forms ([c] [r g b])}
{:doc "Unsets the matrix mode from the camera matrix. See begin-camera.", :name end-camera, :forms ([])}
{:doc "Use the begin-contour and end-contour function to create negative\n  shapes within shapes. These functions can only be within a\n  begin-shape/end-shape pair and they only work with the :p2d and :p3d\n  renderers.", :name end-contour, :forms ([])}
{:doc "Complement to begin-raw; they must always be used together. See\n  the begin-raw docstring for details.", :name end-raw, :forms ([])}
{:doc "May only be called after begin-shape. When end-shape is called,\n  all of image data defined since the previous call to begin-shape is\n  written into the image buffer. The keyword :close may be passed to\n  close the shape (to connect the beginning and the end).", :name end-shape, :forms ([] [mode])}
{:doc "Quits/stops/exits the program.  Rather than terminating\n  immediately, exit will cause the sketch to exit after draw has\n  completed (or after setup completes if called during the setup\n  method). ", :name exit, :forms ([])}
{:doc "Returns Euler's number e (2.71828...) raised to the power of the\n  value parameter.", :name exp, :forms ([val])}
{:doc "Sets the color used to fill shapes. For example, (fill 204 102 0),\n  will specify that all subsequent shapes will be filled with orange.", :name fill-float, :forms ([gray] [gray alpha] [r g b] [r g b alpha])}
{:doc "Sets the color used to fill shapes.", :name fill-int, :forms ([rgb] [rgb alpha])}
{:doc "Sets the color used to fill shapes.", :name fill, :forms ([rgb] [rgb alpha] [r g b] [r g b a])}
{:doc "Originally named filter in Processing Language.\n  Filters the display window with the specified mode and level.\n  Level defines the quality of the filter and mode may be one of the\n  following keywords:\n\n  :threshold - converts the image to black and white pixels depending\n               if they are above or below the threshold defined by\n               the level parameter. The level must be between\n               0.0 (black) and 1.0 (white). If no level is specified,\n               0.5 is used.\n  :gray      - converts any colors in the image to grayscale\n               equivalents. Doesn't work with level.\n  :invert    - sets each pixel to its inverse value. Doesn't work with\n               level.\n  :posterize - limits each channel of the image to the number of\n               colors specified as the level parameter. The parameter can\n               be set to values between 2 and 255, but results are most\n               noticeable in the lower ranges.\n  :blur      - executes a Guassian blur with the level parameter\n               specifying the extent of the blurring. If no level\n               parameter is used, the blur is equivalent to Guassian\n               blur of radius 1.\n  :opaque    - sets the alpha channel to entirely opaque. Doesn't work\n               with level.\n  :erode     - reduces the light areas. Doesn't work with level.\n  :dilate    - increases the light areas.  Doesn't work with level.", :name display-filter, :forms ([mode] [mode level])}
{:doc "Calculates the closest int value that is less than or equal to the\n  value of the parameter. For example, (floor 9.03) returns the value 9.", :name floor, :forms ([n])}
{:doc "Returns a boolean value representing whether the applet has focus.", :name focused, :forms ([])}
{:doc "The system variable frameCount contains the number of frames\n  displayed since the program started. Inside setup() the value is 0\n  and after the first iteration of draw it is 1, etc.", :name frame-count, :forms ([])}
{:doc "Returns the current framerate", :name current-frame-rate, :forms ([])}
{:doc "Specifies a new target framerate (number of frames to be displayed every\n  second). If the processor is not fast enough to maintain the\n  specified rate, it will not be achieved. For example, the function\n  call (frame-rate 30) will attempt to refresh 30 times a second. It\n  is recommended to set the frame rate within setup. The default rate\n  is 60 frames per second.", :name frame-rate, :forms ([new-rate])}
{:doc "Sets a perspective matrix defined through the parameters. Works\n  like glFrustum, except it wipes out the current perspective matrix\n  rather than muliplying itself with it.", :name frustum, :forms ([left right bottom top near far])}
{:doc "Reads the color of any pixel or grabs a section of an image. If no\n  parameters are specified, a copy of entire image is returned. Get the\n  value of one pixel by specifying an x,y coordinate. Get a section of\n  the image by specifying an additional width and height parameter.\n  If the pixel requested is outside of the image window, black is returned.\n  The numbers returned are scaled according to the current color ranges,\n  but only RGB values are returned by this function. For example, even though\n  you may have drawn a shape with (color-mode :hsb), the numbers returned\n  will be in RGB.\n\n  Getting the color of a single pixel with (get x y) is easy, but not\n  as fast as grabbing the data directly using the pixels fn.\n\n  If no img specified - current-graphics is used.", :name get-pixel, :forms ([] [img] [x y] [img x y] [x y w h] [img x y w h])}
{:doc "Extracts the green value from a color, scaled to match current\n  color-mode. This value is always returned as a float so be careful\n  not to assign it to an int value.", :name green, :forms ([col])}
{:doc "Converts a byte, char, int, or color to a String containing the\n  equivalent hexadecimal notation. For example color(0, 102, 153) will\n  convert to the String \"FF006699\". This function can help make your\n  geeky debugging sessions much happier. ", :name hex, :forms ([val] [val num-digits])}
{:doc "Height of the display window. The value of height is zero until\n  size is called.", :name height, :forms ([])}
{:doc "Set various hints and hacks for the renderer. This is used to\n  handle obscure rendering features that cannot be implemented in a\n  consistent manner across renderers. Many options will often graduate\n  to standard features instead of hints over time.\n\n  Options:\n\n  :enable-native-fonts - Use the native version fonts when they are\n    installed, rather than the bitmapped version from a .vlw\n    file. This is useful with the default (or JAVA2D) renderer\n    setting, as it will improve font rendering speed. This is not\n    enabled by default, because it can be misleading while testing\n    because the type will look great on your machine (because you have\n    the font installed) but lousy on others' machines if the identical\n    font is unavailable. This option can only be set per-sketch, and\n    must be called before any use of text-font.\n\n  :disable-native-fonts - Disables native font support.\n\n  :disable-depth-test - Disable the zbuffer, allowing you to draw on\n    top of everything at will. When depth testing is disabled, items\n    will be drawn to the screen sequentially, like a painting. This\n    hint is most often used to draw in 3D, then draw in 2D on top of\n    it (for instance, to draw GUI controls in 2D on top of a 3D\n    interface). Starting in release 0149, this will also clear the\n    depth buffer. Restore the default with :enable-depth-test\n    but note that with the depth buffer cleared, any 3D drawing that\n    happens later in draw will ignore existing shapes on the screen.\n\n  :enable-depth-test - Enables the zbuffer.\n\n  :enable-depth-sort - Enable primitive z-sorting of triangles and\n    lines in :p3d and :opengl rendering modes. This can slow\n    performance considerably, and the algorithm is not yet perfect.\n\n  :disable-depth-sort - Disables hint :enable-depth-sort\n\n  :disable-opengl-errors - Speeds up the OPENGL renderer setting\n     by not checking for errors while running.\n\n  :enable-opengl-errors - Turns on OpenGL error checking\n\n  :enable-depth-mask\n  :disable-depth-mask\n\n  :enable-optimized-stroke\n  :disable-optimized-stroke\n  :enable-retina-pixels\n  :disable-retina-pixels\n  :enable-stroke-perspective\n  :disable-stroke-perspective\n  :enable-stroke-pure\n  :disable-stroke-pure\n  :enable-texture-mipmaps\n  :disable-texture-mipmaps\n", :name hint, :forms ([hint-type])}
{:doc "Returns the current hour as a value from 0 - 23.", :name hour, :forms ([])}
{:doc "Extracts the hue value from a color.", :name hue, :forms ([col])}
{:doc "Displays images to the screen. Processing currently works with GIF,\n  JPEG, and Targa images. The color of an image may be modified with\n  the tint function and if a GIF has transparency, it will maintain\n  its transparency. The img parameter specifies the image to display\n  and the x and y parameters define the location of the image from its\n  upper-left corner. The image is displayed at its original size\n  unless the width and height parameters specify a different size. The\n  image-mode fn changes the way the parameters work. A call to\n  (image-mode :corners) will change the width and height parameters to\n  define the x and y values of the opposite corner of the image.\n\n  Starting with release 0124, when using the default (JAVA2D)\n  renderer, smooth will also improve image quality of resized\n  images.", :name image, :forms ([img x y] [img x y c d])}
{:doc "Originally named filter in Processing Language.\n  Filters given image with the specified mode and level.\n  Level defines the quality of the filter and mode may be one of\n  the following keywords:\n\n  :threshold - converts the image to black and white pixels depending\n               if they are above or below the threshold defined by\n               the level parameter. The level must be between\n               0.0 (black) and 1.0 (white). If no level is specified,\n               0.5 is used.\n  :gray      - converts any colors in the image to grayscale\n               equivalents. Doesn't work with level.\n  :invert    - sets each pixel to its inverse value. Doesn't work with\n               level.\n  :posterize - limits each channel of the image to the number of\n               colors specified as the level parameter. The parameter can\n               be set to values between 2 and 255, but results are most\n               noticeable in the lower ranges.\n  :blur      - executes a Guassian blur with the level parameter\n               specifying the extent of the blurring. If no level\n               parameter is used, the blur is equivalent to Guassian\n               blur of radius 1.\n  :opaque    - sets the alpha channel to entirely opaque. Doesn't work\n               with level.\n  :erode     - reduces the light areas. Doesn't work with level.\n  :dilate    - increases the light areas.  Doesn't work with level.", :name image-filter, :forms ([img mode] [img mode level])}
{:doc "Modifies the location from which images draw. The default mode is :corner.\n   Available modes are:\n\n  :corner  - specifies the location to be the upper left corner and\n             uses the fourth and fifth parameters of image to set the\n             image's width and height.\n\n  :corners - uses the second and third parameters of image to set the\n             location of one corner of the image and uses the fourth\n             and fifth parameters to set the opposite corner.\n\n  :center  - draw images centered at the given x and y position.", :name image-mode, :forms ([mode])}
{:doc "The variable keyCode is used to detect special keys such as the UP,\n  DOWN, LEFT, RIGHT arrow keys and ALT, CONTROL, SHIFT. When checking\n  for these keys, it's first necessary to check and see if the key is\n  coded. This is done with the conditional (= (key) CODED).\n\n  The keys included in the ASCII specification (BACKSPACE, TAB, ENTER,\n  RETURN, ESC, and DELETE) do not require checking to see if they key\n  is coded, and you should simply use the key variable instead of\n  key-code If you're making cross-platform projects, note that the\n  ENTER key is commonly used on PCs and Unix and the RETURN key is\n  used instead on Macintosh. Check for both ENTER and RETURN to make\n  sure your program will work for all platforms.\n\n  For users familiar with Java, the values for UP and DOWN are simply\n  shorter versions of Java's KeyEvent.VK_UP and\n  KeyEvent.VK_DOWN. Other keyCode values can be found in the Java\n  KeyEvent reference.", :name key-code, :forms ([])}
{:doc "true if any key is currently pressed, false otherwise.", :name key-pressed?, :forms ([])}
{:doc "Sets the falloff rates for point lights, spot lights, and ambient\n  lights. The parameters are used to determine the falloff with the\n  following equation:\n\n  d = distance from light position to vertex position\n  falloff = 1 / (CONSTANT + d * LINEAR + (d*d) * QUADRATIC)\n\n  Like fill, it affects only the elements which are created after it\n  in the code. The default value is (light-falloff 1.0 0.0 0.0).\n  Thinking about an ambient light with a falloff can be tricky. It is\n  used, for example, if you wanted a region of your scene to be lit\n  ambiently one color and another region to be lit ambiently by\n  another color, you would use an ambient light with location and\n  falloff. You can think of it as a point light that doesn't care\n  which direction a surface is facing.", :name light-falloff, :forms ([constant linear quadratic])}
{:doc "Calculates a color or colors between two color at a specific\n  increment. The amt parameter is the amount to interpolate between\n  the two values where 0.0 equal to the first point, 0.1 is very near\n  the first point, 0.5 is half-way in between, etc.", :name lerp-color, :forms ([c1 c2 amt])}
{:doc "Calculates a number between two numbers at a specific\n  increment. The amt parameter is the amount to interpolate between\n  the two values where 0.0 equal to the first point, 0.1 is very near\n  the first point, 0.5 is half-way in between, etc. The lerp function\n  is convenient for creating motion along a straight path and for\n  drawing dotted lines.", :name lerp, :forms ([start stop amt])}
{:doc "Sets the default ambient light, directional light, falloff, and\n  specular values. The defaults are:\n\n  (ambient-light 128 128 128)\n  (directional-light 128 128 128 0 0 -1)\n  (light-falloff 1 0 0)\n  (light-specular 0 0 0).\n\n  Lights need to be included in the draw to remain persistent in a\n  looping program. Placing them in the setup of a looping program\n  will cause them to only have an effect the first time through the\n  loop.", :name lights, :forms ([])}
{:doc "Sets the specular color for lights. Like fill, it affects only the\n  elements which are created after it in the code. Specular refers to\n  light which bounces off a surface in a perferred direction (rather\n  than bouncing in all directions like a diffuse light) and is used\n  for creating highlights. The specular quality of a light interacts\n  with the specular material qualities set through the specular and\n  shininess functions.", :name light-specular, :forms ([r g b])}
{:doc "Draws a line (a direct path between two points) to the screen. The\n  version of line with four parameters draws the line in 2D. To color\n  a line, use the stroke function. A line cannot be filled, therefore\n  the fill method will not affect the color of a line. 2D lines are\n  drawn with a width of one pixel by default, but this can be changed\n  with the stroke-weight function. The version with six parameters\n  allows the line to be placed anywhere within XYZ space. ", :name line, :forms ([p1 p2] [x1 y1 x2 y2] [x1 y1 z1 x2 y2 z2])}
{:doc "Loads a font into a variable of type PFont. To load correctly,\n  fonts must be located in the data directory of the current sketch.\n  To create a font to use with Processing use the create-font fn.\n\n  Like load-image and other methods that load data, the load-font fn\n  should not be used inside draw, because it will slow down the sketch\n  considerably, as the font will be re-loaded from the disk (or\n  network) on each frame.\n\n  For most renderers, Processing displays fonts using the .vlw font\n  format, which uses images for each letter, rather than defining them\n  through vector data. When hint :enable-native-fonts is used with the\n  JAVA2D renderer, the native version of a font will be used if it is\n  installed on the user's machine.\n\n  Using create-font (instead of load-font) enables vector data to be\n  used with the JAVA2D (default) renderer setting. This can be helpful\n  when many font sizes are needed, or when using any renderer based on\n  JAVA2D, such as the PDF library.", :name load-font, :forms ([filename])}
{:doc "Loads an image into a variable of type PImage. Four types of\n  images ( .gif, .jpg, .tga, .png) images may be loaded. To load\n  correctly, images must be located in the data directory of the\n  current sketch. In most cases, load all images in setup to preload\n  them at the start of the program. Loading images inside draw will\n  reduce the speed of a program.\n\n  The filename parameter can also be a URL to a file found online.\n\n  If an image is not loaded successfully, the null value is returned\n  and an error message will be printed to the console. The error\n  message does not halt the program, however the null value may cause\n  a NullPointerException if your code does not check whether the value\n  returned from load-image is nil.\n\n  Depending on the type of error, a PImage object may still be\n  returned, but the width and height of the image will be set to\n  -1. This happens if bad image data is returned or cannot be decoded\n  properly. Sometimes this happens with image URLs that produce a 403\n  error or that redirect to a password prompt, because load-image\n  will attempt to interpret the HTML as image data.", :name load-image, :forms ([filename])}
{:doc "Loads a shader into the PShader object. Shaders are compatible with the\n  P2D and P3D renderers, but not with the default renderer.", :name load-shader, :forms ([fragment-filename] [fragment-filename vertex-filename])}
{:doc "Load a geometry from a file as a PShape.", :name load-shape, :forms ([filename])}
{:doc "Calculates the natural logarithm (the base-e logarithm) of a\n  number. This function expects the values greater than 0.0.", :name log, :forms ([val])}
{:doc "Calculates the magnitude (or length) of a vector. A vector is a\n  direction in space commonly used in computer graphics and linear\n  algebra. Because it has no start position, the magnitude of a vector\n  can be thought of as the distance from coordinate (0,0) to its (x,y)\n  value. Therefore, mag is a shortcut for writing (dist 0 0 x y).", :name mag, :forms ([a b] [a b c])}
{:doc "Re-maps a number from one range to another.\n\n  Numbers outside the range are not clamped to 0 and 1, because\n  out-of-range values are often intentional and useful.", :name map-range, :forms ([val low1 high1 low2 high2])}
{:doc "Returns the number of milliseconds (thousandths of a second) since\n  starting the sketch. This information is often used for timing\n  animation sequences.", :name millis, :forms ([])}
{:doc "Returns the current minute as a value from 0 - 59", :name minute, :forms ([])}
{:doc "Returns the three-dimensional x, y, z position in model space. This\n  returns the x value for a given coordinate based on the current set\n  of transformations (scale, rotate, translate, etc.) The x value can\n  be used to place an object in space relative to the location of the\n  original point once the transformations are no longer in use.", :name model-x, :forms ([x y z])}
{:doc "Returns the three-dimensional x, y, z position in model space. This\n  returns the y value for a given coordinate based on the current set\n  of transformations (scale, rotate, translate, etc.) The y value can\n  be used to place an object in space relative to the location of the\n  original point once the transformations are no longer in use.", :name model-y, :forms ([x y z])}
{:doc "Returns the three-dimensional x, y, z position in model space. This\n  returns the z value for a given coordinate based on the current set\n  of transformations (scale, rotate, translate, etc.) The z value can\n  be used to place an object in space relative to the location of the\n  original point once the transformations are no longer in use.", :name model-z, :forms ([x y z])}
{:doc "Returns the current month as a value from 1 - 12.", :name month, :forms ([])}
{:doc "The value of the system variable mouseButton is either :left, :right,\n  or :center depending on which button is pressed. nil if no button pressed", :name mouse-button, :forms ([])}
{:doc "Variable storing if a mouse button is pressed. The value of the\n  system variable mousePressed is true if a mouse button is pressed\n  and false if a button is not pressed.", :name mouse-pressed?, :forms ([])}
{:doc "Current horizontal coordinate of the mouse.", :name mouse-x, :forms ([])}
{:doc "Current vertical coordinate of the mouse.", :name mouse-y, :forms ([])}
{:doc "Hides the cursor from view. Will not work when running the in full\n  screen (Present) mode.", :name no-cursor, :forms ([])}
{:doc "Disables filling geometry. If both no-stroke and no-fill are called,\n  nothing will be drawn to the screen.", :name no-fill, :forms ([])}
{:doc "Returns the Perlin noise value at specified coordinates. Perlin\n  noise is a random sequence generator producing a more natural\n  ordered, harmonic succession of numbers compared to the standard\n  random function. It was invented by Ken Perlin in the 1980s and\n  been used since in graphical applications to produce procedural\n  textures, natural motion, shapes, terrains etc.\n\n  The main difference to the random function is that Perlin noise is\n  defined in an infinite n-dimensional space where each pair of\n  coordinates corresponds to a fixed semi-random value (fixed only for\n  the lifespan of the program). The resulting value will always be\n  between 0.0 and 1.0. Processing can compute 1D, 2D and 3D noise,\n  depending on the number of coordinates given. The noise value can be\n  animated by moving through the noise space and the 2nd and 3rd\n  dimensions can also be interpreted as time.\n\n  The actual noise is structured similar to an audio signal, in\n  respect to the function's use of frequencies. Similar to the concept\n  of harmonics in physics, perlin noise is computed over several\n  octaves which are added together for the final result.\n\n  Another way to adjust the character of the resulting sequence is the\n  scale of the input coordinates. As the function works within an\n  infinite space the value of the coordinates doesn't matter as such,\n  only the distance between successive coordinates does (eg. when\n  using noise within a loop). As a general rule the smaller the\n  difference between coordinates, the smoother the resulting noise\n  sequence will be. Steps of 0.005-0.03 work best for most\n  applications, but this will differ depending on use.", :name noise, :forms ([x] [x y] [x y z])}
{:doc "Adjusts the character and level of detail produced by the Perlin\n  noise function. Similar to harmonics in physics, noise is computed\n  over several octaves. Lower octaves contribute more to the output\n  signal and as such define the overal intensity of the noise, whereas\n  higher octaves create finer grained details in the noise\n  sequence. By default, noise is computed over 4 octaves with each\n  octave contributing exactly half than its predecessor, starting at\n  50% strength for the 1st octave. This falloff amount can be changed\n  by adding an additional function parameter. Eg. a falloff factor of\n  0.75 means each octave will now have 75% impact (25% less) of the\n  previous lower octave. Any value between 0.0 and 1.0 is valid,\n  however note that values greater than 0.5 might result in greater\n  than 1.0 values returned by noise.\n\n  By changing these parameters, the signal created by the noise\n  function can be adapted to fit very specific needs and\n  characteristics.", :name noise-detail, :forms ([octaves] [octaves falloff])}
{:doc "Sets the seed value for noise. By default, noise produces different\n  results each time the program is run. Set the value parameter to a\n  constant to return the same pseudo-random numbers each time the\n  software is run.", :name noise-seed, :forms ([val])}
{:doc "Disable all lighting. Lighting is turned off by default and enabled\n  with the lights fn. This function can be used to disable lighting so\n  that 2D geometry (which does not require lighting) can be drawn\n  after a set of lighted 3D geometry.", :name no-lights, :forms ([])}
{:doc "Stops Processing from continuously executing the code within\n  draw. If start-loop is called, the code in draw will begin to run\n  continuously again. If using no-loop in setup, it should be the last\n  line inside the block.\n\n  When no-loop is used, it's not possible to manipulate or access the\n  screen inside event handling functions such as mouse-pressed or\n  key-pressed. Instead, use those functions to call redraw or\n  loop which will run draw, which can update the screen\n  properly. This means that when no-loop has been called, no drawing\n  can happen, and functions like save-frame may not be used.\n\n  Note that if the sketch is resized, redraw will be called to\n  update the sketch, even after no-oop has been\n  specified. Otherwise, the sketch would enter an odd state until\n  loop was called.", :name no-loop, :forms ([])}
{:doc "Normalize a value to exist between 0 and 1 (inclusive).", :name norm, :forms ([val start stop])}
{:doc "Sets the current normal vector. This is for drawing three\n  dimensional shapes and surfaces and specifies a vector perpendicular\n  to the surface of the shape which determines how lighting affects\n  it. Processing attempts to automatically assign normals to shapes,\n  but since that's imperfect, this is a better option when you want\n  more control. This function is identical to glNormal3f() in OpenGL.", :name normal, :forms ([nx ny nz])}
{:doc "Draws all geometry with jagged (aliased) edges. Clojure: must be\n  called inside :settings function. ClojureScript: can be called\n  anywhere.", :name no-smooth, :forms ([])}
{:doc "Disables drawing the stroke (outline). If both no-stroke and\n  no-fill are called, nothing will be drawn to the screen.", :name no-stroke, :forms ([])}
{:doc "Removes the current fill value for displaying images and reverts to\n  displaying images with their original hues.", :name no-tint, :forms ([])}
{:doc "Sets an orthographic projection and defines a parallel clipping\n  volume. All objects with the same dimension appear the same size,\n  regardless of whether they are near or far from the camera. The\n  parameters to this function specify the clipping volume where left\n  and right are the minimum and maximum x values, top and bottom are\n  the minimum and maximum y values, and near and far are the minimum\n  and maximum z values. If no parameters are given, the default is\n  used: (ortho 0 width 0 height -10 10)", :name ortho, :forms ([] [left right bottom top] [left right bottom top near far])}
{:doc "Sets a perspective projection applying foreshortening, making\n  distant objects appear smaller than closer ones. The parameters\n  define a viewing volume with the shape of truncated pyramid. Objects\n  near to the front of the volume appear their actual size, while\n  farther objects appear smaller. This projection simulates the\n  perspective of the world more accurately than orthographic\n  projection. The version of perspective without parameters sets the\n  default perspective and the version with four parameters allows the\n  programmer to set the area precisely. The default values are:\n  perspective(PI/3.0, width/height, cameraZ/10.0, cameraZ*10.0) where\n  cameraZ is ((height/2.0) / tan(PI*60.0/360.0));", :name perspective, :forms ([] [fovy aspect z-near z-far])}
{:doc "Array containing the values for all the pixels in the display\n  window or image. This array is therefore the size of the display window. If\n  this array is modified, the update-pixels fn must be called to update\n  the changes. Calls .loadPixels before obtaining the pixel array.", :name pixels, :forms ([] [img])}
{:doc "Horizontal coordinate of the mouse in the previous frame", :name pmouse-x, :forms ([])}
{:doc "Vertical coordinate of the mouse in the previous frame", :name pmouse-y, :forms ([])}
{:doc "Draws a point, a coordinate in space at the dimension of one\n  pixel. The first parameter is the horizontal value for the point,\n  the second value is the vertical value for the point, and the\n  optional third value is the depth value. Drawing this shape in 3D\n  using the z parameter requires the :P3D or :opengl renderer to be\n  used.", :name point, :forms ([x y] [x y z])}
{:doc "Adds a point light. Lights need to be included in the draw() to\n  remain persistent in a looping program. Placing them in the setup()\n  of a looping program will cause them to only have an effect the\n  first time through the loop. The affect of the r, g, and b\n  parameters is determined by the current color mode. The x, y, and z\n  parameters set the position of the light", :name point-light, :forms ([r g b x y z])}
{:doc "Pops the current transformation matrix off the matrix\n  stack. Understanding pushing and popping requires understanding the\n  concept of a matrix stack. The push-matrix fn saves the current\n  coordinate system to the stack and pop-matrix restores the prior\n  coordinate system. push-matrix and pop-matrix are used in conjuction\n  with the other transformation methods and may be embedded to control\n  the scope of the transformations.", :name pop-matrix, :forms ([])}
{:doc "Restores the prior settings on the 'style stack'. Used in\n  conjunction with push-style. Together they allow you to change the\n  style settings and later return to what you had. When a new style is\n  started with push-style, it builds on the current style information.\n  The push-style and pop-style functions can be nested to provide more\n  control", :name pop-style, :forms ([])}
{:doc "Facilitates exponential expressions. The pow() function is an\n  efficient way of multiplying numbers by themselves (or their\n  reciprocal) in large quantities. For example, (pow 3 5) is\n  equivalent to the expression (* 3 3 3 3 3) and (pow 3 -5) is\n  equivalent to (/ 1 (* 3 3 3 3 3)).", :name pow, :forms ([num exponent])}
{:doc "Prints the current camera matrix to std out. Useful for debugging.", :name print-camera, :forms ([])}
{:doc "Prints the current matrix to std out. Useful for debugging.", :name print-matrix, :forms ([])}
{:doc "Prints the current projection matrix to std out. Useful for\n  debugging", :name print-projection, :forms ([])}
{:doc "Pushes the current transformation matrix onto the matrix\n  stack. Understanding push-matrix and pop-matrix requires\n  understanding the concept of a matrix stack. The push-matrix\n  function saves the current coordinate system to the stack and\n  pop-matrix restores the prior coordinate system. push-matrix and\n  pop-matrix are used in conjuction with the other transformation\n  methods and may be embedded to control the scope of the\n  transformations.", :name push-matrix, :forms ([])}
{:doc "Saves the current style settings onto a 'style stack'. Use with\n  pop-style which restores the prior settings. Note that these\n  functions are always used together. They allow you to change the\n  style settings and later return to what you had. When a new style is\n  started with push-style, it builds on the current style\n  information. The push-style and pop-style fns can be embedded to\n  provide more control.\n\n  The style information controlled by the following functions are\n  included in the style: fill, stroke, tint, stroke-weight,\n  stroke-cap, stroke-join, image-mode, rect-mode, ellipse-mode,\n  shape-mode, color-mode, text-align, text-font, text-mode, text-size,\n  text-leading, emissive, specular, shininess, and ambient", :name push-style, :forms ([])}
{:doc "A quad is a quadrilateral, a four sided polygon. It is similar to a\n  rectangle, but the angles between its edges are not constrained to\n  be ninety degrees. The first pair of parameters (x1,y1) sets the\n  first vertex and the subsequent pairs should proceed clockwise or\n  counter-clockwise around the defined shape.", :name quad, :forms ([x1 y1 x2 y2 x3 y3 x4 y4])}
{:doc "Specifies vertex coordinates for quadratic Bezier curves. Each call to\n  quadratic-vertex defines the position of one control points and one\n  anchor point of a Bezier curve, adding a new segment to a line or shape.\n  The first time quadratic-vertex is used within a begin-shape call, it\n  must be prefaced with a call to vertex to set the first anchor point.\n  This function must be used between begin-shape and end-shape and only\n  when there is no MODE parameter specified to begin-shape. Using the 3D\n  version requires rendering with :p3d.", :name quadratic-vertex, :forms ([cx cy x3 y3] [cx cy cz x3 y3 z3])}
{:doc "Converts a degree measurement to its corresponding value in\n  radians. Radians and degrees are two ways of measuring the same\n  thing. There are 360 degrees in a circle and 2*PI radians in a\n  circle. For example, 90° = PI/2 = 1.5707964. All trigonometric\n  methods in Processing require their parameters to be specified in\n  radians.", :name radians, :forms ([degrees])}
{:doc "Generates random numbers. Each time the random function is called,\n  it returns an unexpected value within the specified range. If one\n  parameter is passed to the function it will return a float between\n  zero and the value of the high parameter. The function call (random\n  5) returns values between 0 and 5 (starting at zero, up to but not\n  including 5). If two parameters are passed, it will return a float\n  with a value between the parameters. The function call\n  (random -5 10.2) returns values starting at -5 up to (but not\n  including) 10.2.", :name random, :forms ([max] [min max])}
{:doc "Returns a float from a random series of numbers having a mean of 0 and\n  standard deviation of 1. Each time the randomGaussian() function is called,\n  it returns a number fitting a Gaussian, or normal, distribution.\n  There is theoretically no minimum or maximum value that randomGaussian()\n  might return. Rather, there is just a very low probability that values far\n  from the mean will be returned; and a higher probability that numbers near\n  the mean will be returned. .", :name random-gaussian, :forms ([])}
{:doc "Sets the seed value for random. By default, random produces\n  different results each time the program is run. Set the value\n  parameter to a constant to return the same pseudo-random numbers\n  each time the software is run.", :name random-seed, :forms ([w])}
{:doc "Contains the value of the most recent key on the keyboard that was\n  used (either pressed or released).\n\n  For non-ASCII keys, use the keyCode variable. The keys included in\n  the ASCII specification (BACKSPACE, TAB, ENTER, RETURN, ESC, and\n  DELETE) do not require checking to see if they key is coded, and you\n  should simply use the key variable instead of keyCode If you're\n  making cross-platform projects, note that the ENTER key is commonly\n  used on PCs and Unix and the RETURN key is used instead on\n  Macintosh. Check for both ENTER and RETURN to make sure your program\n  will work for all platforms.", :name raw-key, :forms ([])}
{:doc "Draws a rectangle to the screen. A rectangle is a four-sided shape\n  with every angle at ninety degrees. By default, the first two\n  parameters set the location of the upper-left corner, the third\n  sets the width, and the fourth sets the height. These parameters\n  may be changed with rect-mode.\n\n  To draw a rounded rectangle, add a fifth parameter, which is used as\n  the radius value for all four corners. To use a different radius value\n  for each corner, include eight parameters.", :name rect, :forms ([x y width height] [x y width height r] [x y width height top-left-r top-right-r bottom-right-r bottom-left-r])}
{:doc "Modifies the location from which rectangles draw. The default mode\n  is :corner. Available modes are:\n\n\n  :corner  - Specifies the location to be the upper left corner of the\n             shape and uses the third and fourth parameters of rect to\n             specify the width and height.\n\n  :corners - Uses the first and second parameters of rect to set the\n             location of one corner and uses the third and fourth\n             parameters to set the opposite corner.\n\n  :center  - Draws the image from its center point and uses the third\n             and forth parameters of rect to specify the image's width\n             and height.\n\n  :radius  - Draws the image from its center point and uses the third\n             and forth parameters of rect() to specify half of the\n             image's width and height.", :name rect-mode, :forms ([mode])}
{:doc "Extracts the red value from a color, scaled to match current color-mode.", :name red, :forms ([c])}
{:doc "Executes the code within the draw fn one time. This functions\n  allows the program to update the display window only when necessary,\n  for example when an event registered by mouse-pressed or\n  key-pressed occurs.\n\n  In structuring a program, it only makes sense to call redraw\n  within events such as mouse-pressed. This is because redraw does\n  not run draw immediately (it only sets a flag that indicates an\n  update is needed).\n\n  Calling redraw within draw has no effect because draw is\n  continuously called anyway.", :name redraw, :forms ([])}
{:doc "This function load images on a separate thread so that your sketch\n  does not freeze while images load during setup. While the image is\n  loading, its width and height will be 0. If an error occurs while\n  loading the image, its width and height will be set to -1. You'll\n  know when the image has loaded properly because its width and height\n  will be greater than 0. Asynchronous image loading (particularly\n  when downloading from a server) can dramatically improve\n  performance.", :name request-image, :forms ([filename])}
{:doc "Replaces the current matrix with the identity matrix. The\n  equivalent function in OpenGL is glLoadIdentity()", :name reset-matrix, :forms ([])}
{:doc "Resize the image to a new width and height.\n  To make the image scale proportionally, use 0 as the value for the wide or\n  high parameter. For instance, to make the width of an image 150 pixels,\n  and change the height using the same proportion, use resize(150, 0).\n\n  Even though a PGraphics is technically a PImage, it is not possible\n  to rescale the image data found in a PGraphics.\n  (It's simply not possible to do this consistently across renderers:\n  technically infeasible with P3D, or what would it even do with PDF?)\n  If you want to resize PGraphics content, first get a copy of its image data\n  using the get() method, and call resize() on the PImage that is returned.", :name resize, :forms ([img w h])}
{:doc "Rotates a shape the amount specified by the angle parameter. Angles\n  should be specified in radians (values from 0 to TWO-PI) or\n  converted to radians with the radians function.\n\n  Objects are always rotated around their relative position to the\n  origin and positive numbers rotate objects in a clockwise\n  direction. Transformations apply to everything that happens after\n  and subsequent calls to the function accumulates the effect. For\n  example, calling (rotate HALF-PI) and then (rotate HALF-PI) is the\n  same as (rotate PI). All tranformations are reset when draw begins\n  again.\n\n  Technically, rotate multiplies the current transformation matrix by\n  a rotation matrix. This function can be further controlled by the\n  push-matrix and pop-matrix.", :name rotate, :forms ([angle] [angle vx vy vz])}
{:doc "Rotates a shape around the x-axis the amount specified by the angle\n  parameter. Angles should be specified in radians (values from 0 to\n  (* PI 2)) or converted to radians with the radians function. Objects\n  are always rotated around their relative position to the origin and\n  positive numbers rotate objects in a counterclockwise\n  direction. Transformations apply to everything that happens after\n  and subsequent calls to the function accumulates the effect. For\n  example, calling (rotate-x HALF-PI) and then (rotate-x HALF-PI) is\n  the same as (rotate-x PI). If rotate-x is called within the draw fn,\n  the transformation is reset when the loop begins again. This\n  function requires either the :p3d or :opengl renderer.", :name rotate-x, :forms ([angle])}
{:doc "Rotates a shape around the y-axis the amount specified by the angle\n  parameter. Angles should be specified in radians (values from 0\n  to (* PI 2)) or converted to radians with the radians function.\n  Objects are always rotated around their relative position to the\n  origin and positive numbers rotate objects in a counterclockwise\n  direction. Transformations apply to everything that happens after\n  and subsequent calls to the function accumulates the effect. For\n  example, calling (rotate-y HALF-PI) and then (rotate-y HALF-PI) is\n  the same as (rotate-y PI). If rotate-y is called within the draw fn,\n  the transformation is reset when the loop begins again. This\n  function requires either the :p3d or :opengl renderer.", :name rotate-y, :forms ([angle])}
{:doc "Rotates a shape around the z-axis the amount specified by the angle\n  parameter. Angles should be specified in radians (values from 0\n  to (* PI 2)) or converted to radians with the radians function.\n  Objects are always rotated around their relative position to the\n  origin and positive numbers rotate objects in a counterclockwise\n  direction. Transformations apply to everything that happens after\n  and subsequent calls to the function accumulates the effect. For\n  example, calling (rotate-z HALF-PI) and then (rotate-z HALF-PI) is\n  the same as (rotate-z PI). If rotate-y is called within the draw fn,\n  the transformation is reset when the loop begins again. This\n  function requires either the :p3d or :opengl renderer.", :name rotate-z, :forms ([angle])}
{:doc "Calculates the integer closest to the value parameter. For example,\n  (round 9.2) returns the value 9.", :name round, :forms ([val])}
{:doc "Extracts the saturation value from a color.", :name saturation, :forms ([c])}
{:doc "Saves an image from the display window. Images are saved in TIFF,\n  TARGA, JPEG, and PNG format depending on the extension within the\n  filename parameter. For example, image.tif will have a TIFF image\n  and image.png will save a PNG image. If no extension is included in\n  the filename, the image will save in TIFF format and .tif will be\n  added to the name. All images saved from the main drawing window\n  will be opaque. To save images without a background, use\n  create-graphics.", :name save, :forms ([filename])}
{:doc "Saves an image identical to the current display window as a\n  file. May be called multple times - each file saved will have a\n  unique name. Name and image formate may be modified by passing a\n  string parameter of the form \"foo-####.ext\" where foo- can be any\n  arbitrary string, #### will be replaced with the current frame id\n  and .ext is one of .tiff, .targa, .png, .jpeg or .jpg\n\n  Examples:\n  (save-frame)\n  (save-frame \"pretty-pic-####.jpg\")", :name save-frame, :forms ([] [name])}
{:doc "Increases or decreases the size of a shape by expanding and\n  contracting vertices. Objects always scale from their relative\n  origin to the coordinate system. Scale values are specified as\n  decimal percentages. For example, the function call (scale 2)\n  increases the dimension of a shape by 200%. Transformations apply to\n  everything that happens after and subsequent calls to the function\n  multiply the effect. For example, calling (scale 2) and then\n  (scale 1.5) is the same as (scale 3). If scale is called within\n  draw, the transformation is reset when the loop begins again. Using\n  this fuction with the z parameter requires specfying :p3d or :opengl\n  as the renderer. This function can be further controlled by\n  push-matrix and pop-matrix.", :name scale, :forms ([s] [sx sy] [sx sy sz])}
{:doc "Takes a three-dimensional x, y, z position and returns the x value\n  for where it will appear on a (two-dimensional) screen, once\n  affected by translate, scale or any other transformations", :name screen-x, :forms ([x y] [x y z])}
{:doc "Takes a three-dimensional x, y, z position and returns the y value\n  for where it will appear on a (two-dimensional) screen, once\n  affected by translate, scale or any other transformations", :name screen-y, :forms ([x y] [x y z])}
{:doc "Given an x, y, z coordinate, returns its z value.\n   This value can be used to determine if an x, y, z coordinate is in\n   front or in back of another (x, y, z) coordinate. The units are\n   based on how the zbuffer is set up, and don't relate to anything\n   'real'. They're only useful for in comparison to another value\n   obtained from screen-z, or directly out of the zbuffer", :name screen-z, :forms ([x y z])}
{:doc "Returns the current second as a value from 0 - 59.", :name seconds, :forms ([])}
{:doc "Changes the color of any pixel in the display window. The x and y\n  parameters specify the pixel to change and the color parameter\n  specifies the color value. The color parameter is affected by the\n  current color mode (the default is RGB values from 0 to 255).\n\n  Setting the color of a single pixel with (set x, y) is easy, but not\n  as fast as putting the data directly into pixels[].\n\n  This function ignores imageMode().\n\n  Due to what appears to be a bug in Apple's Java implementation, the\n  point() and set() methods are extremely slow in some circumstances\n  when used with the default renderer. Using :p2d or :p3d will fix the\n  problem. Grouping many calls to point or set-pixel together can also\n  help. (Bug 1094)", :name set-pixel, :forms ([x y c] [img x y c])}
{:doc "Writes an image directly into the display window. The x and y\n  parameters define the coordinates for the upper-left corner of the\n  image.", :name set-image, :forms ([x y src])}
{:doc "Displays shapes to the screen. The shapes must have been loaded\n  with load-shape. Processing currently works with SVG shapes\n  only. The sh parameter specifies the shape to display and the x and\n  y parameters define the location of the shape from its upper-left\n  corner. The shape is displayed at its original size unless the width\n  and height parameters specify a different size. The shape-mode\n  fn changes the way the parameters work. A call to\n  (shape-mode :corners), for example, will change the width and height\n  parameters to define the x and y values of the opposite corner of\n  the shape.\n\n  Note complex shapes may draw awkwardly with the renderers :p2d, :p3d, and\n  :opengl. Those renderers do not yet support shapes that have holes\n  or complicated breaks.", :name shape, :forms ([sh] [sh x y] [sh x y width height])}
{:doc "Shears a shape around the x-axis the amount specified by the angle\n  parameter. Angles should be specified in radians (values from 0 to\n  PI*2) or converted to radians with the radians() function. Objects\n  are always sheared around their relative position to the origin and\n  positive numbers shear objects in a clockwise direction.\n  Transformations apply to everything that happens after and\n  subsequent calls to the function accumulates the effect. For\n  example, calling (shear-x (/ PI 2)) and then (shear-x (/ PI 2)) is\n  the same as (shear-x PI). If shear-x is called within the draw fn,\n  the transformation is reset when the loop begins again. This\n  function works in P2D or JAVA2D mode.\n\n  Technically, shear-x multiplies the current transformation matrix\n  by a rotation matrix. This function can be further controlled by the\n  push-matrix and pop-matrix fns.", :name shear-x, :forms ([angle])}
{:doc "Shears a shape around the y-axis the amount specified by the angle\n  parameter. Angles should be specified in radians (values from 0 to\n  PI*2) or converted to radians with the radians() function. Objects\n  are always sheared around their relative position to the origin and\n  positive numbers shear objects in a clockwise direction.\n  Transformations apply to everything that happens after and\n  subsequent calls to the function accumulates the effect. For\n  example, calling (shear-y (/ PI 2)) and then (shear-y (/ PI 2)) is\n  the same as (shear-y PI). If shear-y is called within the draw fn,\n  the transformation is reset when the loop begins again. This\n  function works in P2D or JAVA2D mode.\n\n  Technically, shear-y multiplies the current transformation matrix\n  by a rotation matrix. This function can be further controlled by the\n  push-matrix and pop-matrix fns.", :name shear-y, :forms ([angle])}
{:doc "Modifies the location from which shapes draw. Available modes are\n  :corner, :corners and :center. Default is :corner.\n\n  :corner  - specifies the location to be the upper left corner of the\n             shape and uses the third and fourth parameters of shape\n             to specify the width and height.\n\n  :corners - uses the first and second parameters of shape to set\n             the location of one corner and uses the third and fourth\n             parameters to set the opposite corner.\n\n  :center  - draws the shape from its center point and uses the third\n             and forth parameters of shape to specify the width and\n             height. ", :name shape-mode, :forms ([mode])}
{:doc "Sets the amount of gloss in the surface of shapes. Used in\n  combination with ambient, specular, and emissive in setting\n  the material properties of shapes.", :name shininess, :forms ([shine])}
{:doc "Calculates the sine of an angle. This function expects the values\n  of the angle parameter to be provided in radians (values from 0 to\n  6.28). A float within the range -1 to 1 is returned.", :name sin, :forms ([angle])}
{:doc "Draws all geometry with smooth (anti-aliased) edges. This will slow\n  down the frame rate of the application, but will enhance the visual\n  refinement.\n\n  Clojure: must be called inside :settings function.\n  ClojureScript: can be called anywhere.\n\n  The level parameter (int) increases the level of smoothness with the\n  P2D and P3D renderers. This is the level of over sampling applied to\n  the graphics buffer. The value '2' will double the rendering size\n  before scaling it down to the display size. This is called '2x\n  anti-aliasing.' The value 4 is used for 4x anti-aliasing and 8 is\n  specified for 8x anti-aliasing. If level is set to 0, it will disable\n  all smoothing; it's the equivalent of the function noSmooth().\n  The maximum anti-aliasing level is determined by the hardware of the\n  machine that is running the software.\n\n  Note that smooth will also improve image quality of resized images.", :name smooth, :forms ([] [level])}
{:doc "Sets the specular color of the materials used for shapes drawn to\n  the screen, which sets the color of hightlights. Specular refers to\n  light which bounces off a surface in a perferred direction (rather\n  than bouncing in all directions like a diffuse light). Used in\n  combination with emissive, ambient, and shininess in setting\n  the material properties of shapes.", :name specular, :forms ([gray] [x y z])}
{:doc "Generates a hollow ball made from tessellated triangles.", :name sphere, :forms ([radius])}
{:doc "Controls the detail used to render a sphere by adjusting the number\n  of vertices of the sphere mesh. The default resolution is 30, which\n  creates a fairly detailed sphere definition with vertices every\n  360/30 = 12 degrees. If you're going to render a great number of\n  spheres per frame, it is advised to reduce the level of detail using\n  this function. The setting stays active until sphere-detail is\n  called again with a new parameter and so should not be called prior\n  to every sphere statement, unless you wish to render spheres with\n  different settings, e.g. using less detail for smaller spheres or\n  ones further away from the camera. To controla the detail of the\n  horizontal and vertical resolution independently, use the version of\n  the functions with two parameters.", :name sphere-detail, :forms ([res] [ures vres])}
{:doc "Adds a spot light. Lights need to be included in the draw to\n  remain persistent in a looping program. Placing them in the setup\n  of a looping program will cause them to only have an effect the\n  first time through the loop. The affect of the r, g, and b\n  parameters is determined by the current color mode. The x, y, and z\n  parameters specify the position of the light and nx, ny, nz specify\n  the direction or light. The angle parameter affects angle of the\n  spotlight cone.", :name spot-light, :forms ([r g b x y z nx ny nz angle concentration] [[r g b] [x y z] [nx ny nz] angle concentration])}
{:doc "Squares a number (multiplies a number by itself). The result is\n  always a positive number, as multiplying two negative numbers always\n  yields a positive result. For example, -1 * -1 = 1.", :name sq, :forms ([a])}
{:doc "Calculates the square root of a number. The square root of a number\n  is always positive, even though there may be a valid negative\n  root. The square root s of number a is such that (= a (* s s)) . It\n  is the opposite of squaring.", :name sqrt, :forms ([a])}
{:doc "Causes Processing to continuously execute the code within\n  draw. If no-loop is called, the code in draw stops executing.", :name start-loop, :forms ([])}
{:doc "Sets the color used to draw lines and borders around\n  shapes. Converts all args to floats", :name stroke-float, :forms ([gray] [gray alpha] [x y z] [x y z a])}
{:doc "Sets the color used to draw lines and borders around\n  shapes. Converts rgb to int and alpha to a float.", :name stroke-int, :forms ([rgb] [rgb alpha])}
{:doc "Sets the color used to draw lines and borders around shapes. This\n  color is either specified in terms of the RGB or HSB color depending\n  on the current color-mode (the default color space is RGB, with\n  each value in the range from 0 to 255).", :name stroke, :forms ([rgb] [rgb alpha] [x y z] [x y z a])}
{:doc "Sets the style for rendering line endings. These ends are either\n  squared, extended, or rounded and specified with the corresponding\n  parameters :square, :project, and :round. The default cap is :round.", :name stroke-cap, :forms ([cap-mode])}
{:doc "Sets the style of the joints which connect line\n  segments. These joints are either mitered, beveled, or rounded and\n  specified with the corresponding parameters :miter, :bevel, and\n  :round. The default joint is :miter.\n\n  This function is not available with the :p2d, :p3d, or :opengl\n  renderers.", :name stroke-join, :forms ([join-mode])}
{:doc "Sets the width of the stroke used for lines, points, and the border\n  around shapes. All widths are set in units of pixels. ", :name stroke-weight, :forms ([weight])}
{:doc "Calculates the ratio of the sine and cosine of an angle. This\n  function expects the values of the angle parameter to be provided in\n  radians (values from 0 to PI*2). Values are returned in the range\n  infinity to -infinity.", :name tan, :forms ([angle])}
{:doc "Returns the target framerate specified with the fn frame-rate", :name target-frame-rate, :forms ([])}
{:doc "Draws a char to the screen in the specified position. See text fn\n  for more details.", :name text-char, :forms ([c x y] [c x y z])}
{:doc "Draws a number to the screen in the specified position. See text fn\n  for more details.", :name text-num, :forms ([num x y] [num x y z])}
{:doc "Draws text to the screen in the position specified by the x and y\n  parameters and the optional z parameter. A default font will be used\n  unless a font is set with the text-font fn. Change the color of the\n  text with the fill fn. The text displays in relation to the\n  text-align fn, which gives the option to draw to the left, right, and\n  center of the coordinates.\n\n  The x1, y1, x2 and y2 parameters define a\n  rectangular area to display within and may only be used with string\n  data. For text drawn inside a rectangle, the coordinates are\n  interpreted based on the current rect-mode setting.", :name text, :forms ([s x y] [s x y z] [s x1 y1 x2 y2])}
{:doc "Sets the current alignment for drawing text. Available modes are:\n\n  horizontal - :left, :center, and :right\n  vertical   - :top, :bottom, :center, and :baseline\n\n  An optional second parameter specifies the vertical alignment\n  mode. :baseline is the default. The :top and :center parameters are\n  straightforward. The :bottom parameter offsets the line based on the\n  current text-descent. For multiple lines, the final line will be\n  aligned to the bottom, with the previous lines appearing above it.\n\n  When using text with width and height parameters, :baseline is\n  ignored, and treated as :top. (Otherwise, text would by default draw\n  outside the box, since :baseline is the default setting. :baseline is\n  not a useful drawing mode for text drawn in a rectangle.)\n\n  The vertical alignment is based on the value of text-ascent, which\n  many fonts do not specify correctly. It may be necessary to use a\n  hack and offset by a few pixels by hand so that the offset looks\n  correct. To do this as less of a hack, use some percentage of\n  text-ascent or text-descent so that the hack works even if you\n  change the size of the font.", :name text-align, :forms ([align] [align-x align-y])}
{:doc "Returns the ascent of the current font at its current size. This\n  information is useful for determining the height of the font above\n  the baseline. For example, adding the text-ascent and text-descent\n  values will give you the total height of the line.", :name text-ascent, :forms ([])}
{:doc "Returns descent of the current font at its current size. This\n  information is useful for determining the height of the font below\n  the baseline. For example, adding the text-ascent and text-descent\n  values will give you the total height of the line.", :name text-descent, :forms ([])}
{:doc "Sets the current font that will be drawn with the text\n  function. Fonts must be loaded with load-font before it can be\n  used. This font will be used in all subsequent calls to the text\n  function. If no size parameter is input, the font will appear at its\n  original size until it is changed with text-size.\n\n  Because fonts are usually bitmaped, you should create fonts at the\n  sizes that will be used most commonly. Using textFont without the\n  size parameter will result in the cleanest-looking text.\n\n  With the default (JAVA2D) and PDF renderers, it's also possible to\n  enable the use of native fonts via the command\n  (hint :enable-native-fonts). This will produce vector text in JAVA2D\n  sketches and PDF output in cases where the vector data is available:\n  when the font is still installed, or the font is created via the\n  create-font fn", :name text-font, :forms ([font] [font size])}
{:doc "Sets the spacing between lines of text in units of pixels. This\n  setting will be used in all subsequent calls to the text function.", :name text-leading, :forms ([leading])}
{:doc "Sets the way text draws to the screen - available modes\n  are :model and :shape\n\n  In the default configuration (the :model mode), it's possible to\n  rotate, scale, and place letters in two and three dimensional space.\n\n  The :shape mode draws text using the glyph outlines of individual\n  characters rather than as textures. This mode is only supported with\n  the PDF and OPENGL renderer settings. With the PDF renderer, you\n  must specify the :shape text-mode before any other drawing occurs.\n  If the outlines are not available, then :shape will be ignored and\n  :model will be used instead.\n\n  The :shape option in OPENGL mode can be combined with begin-raw to\n  write vector-accurate text to 2D and 3D output files, for instance\n  DXF or PDF. :shape is not currently optimized for OPENGL, so if\n  recording shape data, use :model until you're ready to capture the\n  geometry with begin-raw.", :name text-mode, :forms ([mode])}
{:doc "Sets the current font size. This size will be used in all\n  subsequent calls to the text fn. Font size is measured in\n  units of pixels.", :name text-size, :forms ([size])}
{:doc "Sets a texture to be applied to vertex points. The texture fn must\n  be called between begin-shape and end-shape and before any calls to\n  vertex.\n\n  When textures are in use, the fill color is ignored. Instead, use\n  tint to specify the color of the texture as it is applied to the\n  shape.", :name texture, :forms ([img])}
{:doc "Sets the coordinate space for texture mapping. There are two\n  options, :image and :normal.\n\n  :image refers to the actual coordinates of the image and :normal\n  refers to a normalized space of values ranging from 0 to 1. The\n  default mode is :image. In :image, if an image is 100 x 200 pixels,\n  mapping the image onto the entire size of a quad would require the\n  points (0,0) (0,100) (100,200) (0,200). The same mapping in\n  NORMAL_SPACE is (0,0) (0,1) (1,1) (0,1).", :name texture-mode, :forms ([mode])}
{:doc "Calculates and returns the width of any text string.", :name text-width, :forms ([data])}
{:doc "Sets the fill value for displaying images. Images can be tinted to\n  specified colors or made transparent by setting the alpha.\n\n  To make an image transparent, but not change it's color, use white\n  as the tint color and specify an alpha value. For instance,\n  tint(255, 128) will make an image 50% transparent (unless\n  colorMode() has been used).\n\n  The value for the parameter gray must be less than or equal to the\n  current maximum value as specified by colorMode(). The default\n  maximum value is 255.\n\n  Also used to control the coloring of textures in 3D.", :name tint-float, :forms ([gray] [gray alpha] [r g b] [r g b a])}
{:doc "Sets the fill value for displaying images. Images can be tinted to\n  specified colors or made transparent by setting the alpha.\n\n  To make an image transparent, but not change it's color, use white\n  as the tint color and specify an alpha value. For instance,\n  tint(255, 128) will make an image 50% transparent (unless\n  colorMode() has been used).\n\n  The value for the parameter gray must be less than or equal to the\n  current maximum value as specified by colorMode(). The default\n  maximum value is 255.\n\n  Also used to control the coloring of textures in 3D.", :name tint-int, :forms ([rgb] [rgb alpha])}
{:doc "Sets the fill value for displaying images. Images can be tinted to\n  specified colors or made transparent by setting the alpha.\n\n  To make an image transparent, but not change it's color, use white\n  as the tint color and specify an alpha value. For instance,\n  tint(255, 128) will make an image 50% transparent (unless\n  colorMode() has been used).\n\n  The value for the parameter gray must be less than or equal to the\n  current maximum value as specified by colorMode(). The default\n  maximum value is 255.\n\n  Also used to control the coloring of textures in 3D.", :name tint, :forms ([rgb] [rgb alpha] [r g b] [r g b a])}
{:doc "Specifies an amount to displace objects within the display\n  window. The x parameter specifies left/right translation, the y\n  parameter specifies up/down translation, and the z parameter\n  specifies translations toward/away from the screen.  Transformations\n  apply to everything that happens after and subsequent calls to the\n  function accumulates the effect. For example, calling (translate 50\n  0) and then (translate 20, 0) is the same as (translate 70, 0). If\n  translate is called within draw, the transformation is reset when\n  the loop begins again. This function can be further controlled by\n  the push-matrix and pop-matrix.", :name translate, :forms ([v] [tx ty] [tx ty tz])}
{:doc "A triangle is a plane created by connecting three points. The first\n  two arguments specify the first point, the middle two arguments\n  specify the second point, and the last two arguments specify the\n  third point.", :name triangle, :forms ([x1 y1 x2 y2 x3 y3])}
{:doc "Unpack a binary string to an integer. See binary for converting\n  integers to strings.", :name unbinary, :forms ([str-val])}
{:doc "Converts a String representation of a hexadecimal number to its\n  equivalent integer value.", :name unhex, :forms ([hex-str])}
{:doc "Updates the display window or image with the data in the pixels array.\n  Use in conjunction with (pixels). If you're only reading pixels from\n  the array, there's no need to call update-pixels unless there are\n  changes.\n\n  Certain renderers may or may not seem to require pixels or\n  update-pixels. However, the rule is that any time you want to\n  manipulate the pixels array, you must first call pixels, and\n  after changes have been made, call update-pixels. Even if the\n  renderer may not seem to use this function in the current Processing\n  release, this will always be subject to change.", :name update-pixels, :forms ([] [img])}
{:doc "All shapes are constructed by connecting a series of\n  vertices. vertex is used to specify the vertex coordinates for\n  points, lines, triangles, quads, and polygons and is used\n  exclusively within the begin-shape and end-shape fns.\n\n  Drawing a vertex in 3D using the z parameter requires the :p3d or\n  :opengl renderers to be used.\n\n  This function is also used to map a texture onto the geometry. The\n  texture fn declares the texture to apply to the geometry and the u\n  and v coordinates set define the mapping of this texture to the\n  form. By default, the coordinates used for u and v are specified in\n  relation to the image's size in pixels, but this relation can be\n  changed with texture-mode.", :name vertex, :forms ([x y] [x y z] [x y u v] [x y z u v])}
{:doc "Returns the current year as an integer (2003, 2004, 2005, etc).", :name year, :forms ([])}
{:doc "Width of the display window. The value of width is zero until size is\n  called.", :name width, :forms ([])}
{:doc "Create and start a new visualisation applet. Can be used to create\n  new sketches programmatically. See documentation for 'defsketch' for\n  list of available options.", :name sketch, :forms ([& opts])}
{:doc "Returns true if char c is a 'coded' char i.e. it is necessary to\n  fetch the key-code as an integer and use that to determine the\n  specific key pressed. See key-keyword.", :name key-coded?, :forms ([c])}
{:doc "Returns a keyword representing the currently pressed key. Modifier\n  keys are represented as: :up, :down, :left, :right, :alt, :control,\n  :shift, :command, :f1-24", :name key-as-keyword, :forms ([])}]))